version: '3.9'

services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    restart: unless-stopped
    networks:
      - public_network
      - private_network
    environment:
      GLPI_DB_HOST: db
      GLPI_DB_NAME: bdd_glpi
      GLPI_DB_USER: user1
      GLPI_DB_PASSWORD: donttouchmydb
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: bdd_glpi
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bdd_glpi
      MYSQL_USER: user1
      MYSQL_PASSWORD: donttouchmydb
    networks:
      - private_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8085:80" # Expose Nginx uniquement sur le port 8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - public_network
    depends_on:
      - glpi

volumes:
  db_data:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
